### ISSUE TITLE
Unable to initialize command with custom target

### ISSUE THREAD

**Issue by twodayslate** [oasis-open/openc2-lycan-python#30]
```python
import openc2
import stix2
import json
import collections

class CustomTargetProperty(openc2.base._OpenC2Base):
    _type = "x-whatever"
    _properties = collections.OrderedDict([
        ("uid", stix2.properties.StringProperty()),
        ("name", stix2.properties.StringProperty()),
        ("version", stix2.properties.StringProperty())])

    def _check_object_constraints(self):
        super(CustomTargetProperty, self)._check_object_constraints()
        self._check_at_least_one_property()

@openc2.CustomTarget(
    "x-thing:id", [('id', stix2.properties.EmbeddedObjectProperty(CustomTargetProperty))]
)
class CustomTarget(object):
    pass

t = CustomTarget(id=CustomTargetProperty(name="twodayslate"))

cmd = openc2.Command(action="query", target=t)

d = json.loads(cmd.serialize())
print(d)
cmd = openc2.Command(**d) # fails even when allows_custom=True

print(cmd)
```

```bash
% python ./test.py
{'action': 'query', 'target': {'x-thing:id': {'name': 'twodayslate'}}}
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/stix2/base.py", line 99, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/openc2/properties.py", line 94, in clean
    parsed_obj = parse_component(dictified, allow_custom=self.allow_custom, component_type=self._component_type)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/openc2/core.py", line 98, in parse_component
    return obj_class(allow_custom=allow_custom, **obj)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/openc2/custom.py", line 59, in __init__
    _Target.__init__(self, **kwargs)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/openc2/base.py", line 57, in __init__
    super(_OpenC2Base, self).__init__(allow_custom, **kwargs)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/stix2/base.py", line 163, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for _CustomTarget: (name).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./test.py", line 30, in <module>
    cmd = openc2.Command(**d) # fails even when allows_custom=True
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/openc2/base.py", line 57, in __init__
    super(_OpenC2Base, self).__init__(allow_custom, **kwargs)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/stix2/base.py", line 182, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/Users/user/.pyenv/versions/kube/lib/python3.7/site-packages/stix2/base.py", line 109, in _check_property
    exc,
  File "<string>", line 3, in raise_from
stix2.exceptions.InvalidValueError: Invalid value for Command 'target': Unexpected properties for _CustomTarget: (name).
```

I would expect that `openc2.Command` could parse the result and a valid command could be produced. Is this an incorrect expectation? I understand that target is not of type `CustomTargetProperty` and is instead a `dict` but with the extension prefix `openc2.Command` should know what it is supposed to be. 

This appears to fix it although probably specific to my test case https://pastebin.com/Rm8b3UkG

**Comment by mstair** [comment]
You have the correct expectation, appears to be a bug in the custom object parsing. OpenC2 is flatter than the STIX2 json, so I had to do some tricks to get extensions/custom working. I'll take a look (thanks for the pastebin).

**Comment by twodayslate** [comment]
The bug's flow is in `ComponentProperty`->`clean`->`parse_component`

I'm sure `parse_args` has a similar problem but I haven't written any test cases for that yet to confirm.

If there is an approved/better way to structure my data above instead of using `EmbeddedObjectProperty` please let me know. It seems to also fail with `DictionaryProperty` instead of `EmbeddedObjectProperty` which surprised me. https://pastebin.com/NsQj5RzW

Tried again with a custom property wrapper https://pastebin.com/0y8Keze6 https://pastebin.com/NaFwJ2Kp
