### ISSUE TITLE
Example Throws InvalidValueError for Command IPv4Address

### ISSUE THREAD

**Issue by maroberts82** [oasis-open/openc2-lycan-python#46]
I tried out the example on the readme, it's throwing the following error though:
`stix2.exceptions.InvalidValueError: Invalid value for Command 'target': ComponentProperty.clean() takes 2 positional arguments but 3 were given`

Here's for full error stack:
```
$  cd /.../WebValidator/server/tests/test_message_creation.py 
start
encode_msg...
Traceback (most recent call last):
  File "/home/.../.virtualenvs/webvalidator/lib/python3.10/site-packages/stix2/base.py", line 50, in _check_property
    kwargs[prop_name], has_custom = prop.clean(
TypeError: ComponentProperty.clean() takes 2 positional arguments but 3 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/.../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/.../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/.../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/..../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/..../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/.../.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/.../screamingbunny/Schema/WebValidator/server/tests/test_message_creation.py", line 20, in <module>
    msg = encode_msg()
  File "/home/.../screamingbunny/Schema/WebValidator/server/tests/test_message_creation.py", line 5, in encode_msg
    cmd = openc2.v10.Command(
  File "/home/.../.virtualenvs/webvalidator/lib/python3.10/site-packages/openc2/base.py", line 59, in __init__
    super(_OpenC2Base, self).__init__(allow_custom, **kwargs)
  File "/home/.../.virtualenvs/webvalidator/lib/python3.10/site-packages/stix2/base.py", line 203, in __init__
    temp_custom = self._check_property(
  File "/home/.../.virtualenvs/webvalidator/lib/python3.10/site-packages/stix2/base.py", line 58, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Command 'target': ComponentProperty.clean() takes 2 positional arguments but 3 were given
```

Here's my very simple test taken from the readme.
```
import openc2

def encode_msg():
    print('encode_msg...')
    cmd = openc2.v10.Command(
        action="deny",
        target=openc2.v10.IPv4Address(ipv4_net="1.2.3.4"),
        args=openc2.v10.Args(response_requested="complete"),
    )
    msg = cmd.serialize(True)
    return msg

def decode_msg(msg):
    print('decode_msg...')
    cmd = openc2.parse(msg)
    return cmd

if __name__ == "__main__":
    print('start')
    msg = encode_msg()
    print('encoded msg: ' + msg)
    cmd = decode_msg()
    print('decoded msg: ' + cmd.target.type)
```

**Comment by RabbITCybErSeC** [comment]
I can confirm this issue. Is the code base only compatible with Python 3.6 or also the Python versions > 3.6?

**Comment by princesaroj111** [comment]
Fix: https://github.com/oasis-open/openc2-lycan-python/pull/48
